<a href="https://colab.research.google.com/github/rifat-mukul/Python-ML-Toolkit/blob/main/Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
x,y = load_breast_cancer(return_X_y=True)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [4]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier #strongest one


# all of them have the same job
clf = RandomForestClassifier()
clf.fit(x_train_scaled,y_train)

RandomForestClassifier()

In [18]:
clf.score(x_test_scaled,y_test)
#

0.9649122807017544

In [19]:
single_instance = x_test_scaled[0]
single_instance

array([-0.46649743, -0.13728933, -0.44421138, -0.48646498,  0.28085007,
        0.04160589, -0.11146496, -0.26486866,  0.41524141,  0.13513744,
       -0.02091509, -0.29323907, -0.17460869, -0.2072995 , -0.01181432,
       -0.35108921, -0.1810535 , -0.24238831, -0.33731758, -0.0842133 ,
       -0.2632354 , -0.14784208, -0.33154752, -0.35109337,  0.48001942,
       -0.09649594, -0.03583041, -0.19435087,  0.17275669,  0.20372995])

In [20]:
clf.predict([single_instance])

array([1])

In [21]:
y_test[0]

np.int64(1)

In [22]:
clf.predict_proba([single_instance])

array([[0.04, 0.96]])